from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# Configuration for titanicsoft database
DT_CONFIG = {
    'TIMEZONE': os.getenv('DT_TIMEZONE'),
    'DAYSOFMARGIN_IMPORT': int(os.getenv('DT_DAYSOFMARGIN_IMPORT', 15)),
    'DAYSOFMARGIN_ASSIGNDELIVERYDATE': int(os.getenv('DT_DAYSOFMARGIN_ASSIGNDELIVERYDATE', 15)),
    'DAYSOFMARGIN_EMBARKEDTODESTINATIONDATE': int(os.getenv('DT_DAYSOFMARGIN_EMBARKEDTODESTINATIONDATE', 15)),
    'DAYSOFMARGIN_DISEMBARKEDATDESTINATION': int(os.getenv('DT_DAYSOFMARGIN_DISEMBARKEDATDESTINATION', 15)),
    'DAYSOFMARGIN_ASSIGNDELIVERED': int(os.getenv('DT_DAYSOFMARGIN_ASSIGNDELIVERED', 15))
}
